services:
  db:
    image: mariadb
    volumes:
      - ./sql_init:/docker-entrypoint-initdb.d
      - db_data:/var/lib/mysql
    restart: always
    environment:
      MARIADB_ALLOW_EMPTY_ROOT_PASSWORD: true
    ports:
      - 3306:3306

  accountManagement:
    image: caengnp/etia1_accountmanagement
    ports:
      - 21801:21801

  tripHistory:
    image: caengnp/etia1_triphistory
    ports:
      - 21802:21802

  tripManagement:
    image: caengnp/etia1_tripmanagement
    ports:
      - 21803:21803

volumes:
  db_data:
